apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
spec:
  type: NodePort
  selector:
    app: minecraft-bedrock
  ports:
  - name: minecraft
    port: 19132
    targetPort: 19132
    nodePort: 30132
    protocol: UDP