apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 30000   # accessible on this port via Pis IP