apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrock-permissions
data:
  permissions.json: |
    [
      {
        "permission": "operator",
        "xuid": "",
        "name": "nzcpaton"
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      containers:
      - name: minecraft-bedrock
        image: itzg/minecraft-bedrock-server:latest
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - name: bedrock-data
          mountPath: /data
        - name: bedrock-permissions
          mountPath: /data/permissions.json
          subPath: permissions.json
      volumes:
      - name: bedrock-data
        persistentVolumeClaim:
          claimName: bedrock-pvc
      - name: bedrock-permissions
        configMap:
          name: bedrock-permissions
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bedrock-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
spec:
  type: NodePort
  selector:
    app: minecraft-bedrock
  ports:
  - name: minecraft
    port: 19132
    targetPort: 19132
    nodePort: 30132
    protocol: UDP